---

- name: Ensure jenkins home dir is created
  file:
    path=/data/jenkins
    mode=0775
    owner={{ ansible_user }}
    group={{ ansible_usergroup }}
    state="directory"
    recurse=yes

- name: run docker jenkins
  docker_container:
    name: jenkins
    image: jenkins
    ports:
      - "8080:8080"
    volumes: /data/jenkins:/var/jenkins_home